(define (make-rand)
  (define seed (random 100))
  (let ((a 1103515245)
        (b 12345)
        (m 4294967296))
   (define (rand symbol)
     (cond ((eq? symbol 'generate)
              (set! seed (remainder (+ (* seed a) b) m))
              (remainder (quotient seed 65536) 32768))
           ((eq? symbol 'reset)
            (lambda (new-seed)
              (set! seed new-seed)))
           (else
             (error "Unsupported operation -- RAND" symbol))))
   rand))

(define rand (make-rand))
